import { type PropsWithChildren } from 'react';

import { type Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Next.js Application',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning>
        <div id="glasseson" />
        {children}
      </body>
    </html>
  );
}
