/* eslint-disable */
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export interface FunctionalWidget<TConfigJson> {
  name: string;
  description?: string;
  componentType: string;
  configJson?: TConfigJson;
}

export interface PLPPageAsset<THeaderContent, TBodyContent, TFooterContent, TConfigJson> {
  name: string;
  description?: string;
  metaTitle?: string;
  metaDescription?: string;
  ogType?: string;
  ogImage?: string;
  url: string;
  pageType: string;
  headerContent?: THeaderContent;
  bodyContent?: TBodyContent[];
  footerContent?: TFooterContent;
  configJson?: TConfigJson;
}

export interface ContentGroup<TContent, TConfigJson> {
  name: string;
  componentType: string;
  content?: TContent[];
  configJson?: TConfigJson;
}

export interface PageTemplate<THeaderContent, TBodyContent, TFooterContent> {
  name: string;
  description?: string;
  templateType: string;
  headerContent?: THeaderContent[];
  bodyContent?: TBodyContent[];
  footerContent?: TFooterContent[];
}

export type Locales = "en-US" 
